# Site settings
title: Agnese Giacomello
email: agnese.giacomello@gmail.com
url: https://AgneseG.github.io
description: “As I see it, statistics is the logical way to understand reality.       I have always been fascinated by the world of numbers and modelling and by how it can shape the reality we are surrounded by, unfolding patterns and meaningful information”


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Agnese Giacomello 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/agnese-giacomello
  - title: stack-overflow
    url: https://stackoverflow.com/users/10363916/agnese-giacomello
  - title: github
    url: https://github.com/AgneseG

# Build settings
markdown: kramdown
permalink: pretty

